/*
 * Sample API
 *
 * A sample API to illustrate OpenAPI concepts
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import "time"

type AggregatedmessagesBatches struct {
	Destination string `json:"destination,omitempty"`

	Messages []AggregatedmessagesMessages `json:"messages,omitempty"`
}

type AggregatedmessagesBody struct {
	Batches []AggregatedmessagesBatches `json:"batches,omitempty"`
}

type AggregatedmessagesMessages struct {
	Text string `json:"text,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`
}

type InlineResponse4Xx struct {
	ErrorCode string `json:"errorCode,omitempty"`

	Message string `json:"message,omitempty"`
}

type InlineResponse5Xx struct {
	ErrorCode string `json:"errorCode,omitempty"`

	Message string `json:"message,omitempty"`
}

type MessageBody struct {
	// The message destination
	Destination string `json:"destination,omitempty"`

	Text string `json:"text,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`
}
